### ISSUE TITLE
PetrovichElixir?

### ISSUE THREAD

**Issue by dustalov** [petrovich/petrovich_elixir#2]
I believe you can use just `Petrovich` instead of `PetrovichElixir`.

**Comment by sobolevn** [comment]
Sure!

**Comment by sobolevn** [comment]
Found out it is not possible to change the main module name: https://github.com/petrovich/petrovich_elixir/commit/42b01d4bdeb82b13b576adf81a7e726c025e69e9

**Comment by dustalov** [comment]
I am not an expert in Elixir. Why was not it possible?

**Comment by sobolevn** [comment]
Solved.
